<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2026 - present - Francois Papon - https://github.com/fpapon
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.openobject.labs.springbootreact</groupId>
    <artifactId>parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Webapp Springboot React</name>

    <organization>
        <name>Francois Papon</name>
        <url>https://github.com/fpapon</url>
    </organization>

    <inceptionYear>2026 - present</inceptionYear>

    <scm>
        <connection>scm:git:https://github.com/fpapon/webapp-springboot-react.git</connection>
        <developerConnection>scm:git:https://github.com/fpapon/webapp-springboot-react.git</developerConnection>
        <url>https://github.com/fpapon/webapp-springboot-react.git</url>
        <tag>HEAD</tag>
    </scm>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://github.com/fpapon/fusion/blob/master/LICENSE</url>
            <distribution>may be downloaded from the Maven repository</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Francois Papon</name>
            <id>fpapon</id>
            <roles>
                <role>Contributor</role>
            </roles>
            <timezone>+1</timezone>
        </developer>
    </developers>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.outputTimestamp>2026-03-07T16:26:39Z</project.build.outputTimestamp>

        <!-- backend -->
        <spring-boot.version>4.0.2</spring-boot.version>
        <spring-boot-maven-plugin.version>4.0.2</spring-boot-maven-plugin.version>

        <!-- frontend -->
        <node.version>v20.11.0</node.version>
        <npm.version>10.2.4</npm.version>
    </properties>

    <modules>
        <module>frontend</module>
        <module>backend</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.5.0</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>frontend/dist</directory>
                        </fileset>
                        <fileset>
                            <directory>frontend/node</directory>
                        </fileset>
                        <fileset>
                            <directory>frontend/node_modules</directory>
                        </fileset>
                        <fileset>
                            <directory>frontend/webapp</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.5.0</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.5.0</version>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <id>enforce-maven</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>3.9.0</version>
                                </requireMavenVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                    <encoding>UTF-8</encoding>
                    <parameters>true</parameters>
                    <proc>full</proc>
                    <compilerArgs>
                        <compilerArg>-Xlint:unchecked</compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>4.5</version>
                <executions>
                    <execution>
                        <id>check-license</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <inherited>false</inherited>
                <configuration>
                    <aggregate>true</aggregate>
                    <mapping>
                        <adoc>DOUBLESLASH_STYLE</adoc>
                    </mapping>
                    <licenseSets>
                        <licenseSet>
                            <inlineHeader><![CDATA[Copyright (c) ${project.inceptionYear} - ${project.organization.name} - ${project.organization.url}
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
]]></inlineHeader>
                            <useDefaultExcludes>true</useDefaultExcludes>
                            <includes>
                                <include>**/*.properties</include>
                                <include>**/*.java</include>
                                <include>**/*.xml</include>
                                <include>**/*.yaml</include>
                            </includes>
                            <excludes>
                                <exclude>LICENSE</exclude>
                                <exclude>**/*.adoc</exclude>
                                <exclude>**/*.idea</exclude>
                                <exclude>**/target/**</exclude>
                                <exclude>**/generated/**</exclude>
                                <exclude>**/minisite/**</exclude>
                                <exclude>**/file</exclude>
                                <exclude>**/.m2/**</exclude>
                            </excludes>
                        </licenseSet>
                    </licenseSets>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
